---
title: "LI6800 output analysis"
author: "Loïc Talide"
output:
  flexdashboard::flex_dashboard:
    orientation: columns
    social: NULL
    source_code: NULL
    self_contained: TRUE
    theme: sandstone
    quiet: TRUE
runtime: shiny
---


```{r CHECK_LIBRARIES, message=FALSE, include=FALSE}
source("Required_libraries.R")
```

```{r DATA _SELECTION, message=FALSE, warning=FALSE, include=FALSE}
if (dir.exists("Z:\\logs")) {
  setwd("Z:\\logs")
} else if (dir.exists("Y:\\logs")) {
  setwd("Y:\\logs")
} else {
  print("No LI6800 unit connected")
}

selected_file <- file.choose()
dateoffile <- readLines(selected_file, n=2)
date_line <- dateoffile[2]
date_string <- strsplit(date_line, "\t")[[1]][2]
file_date <- as.Date(date_string)

header_lines <- readLines(selected_file, n = 62)
data <- as.data.frame(read.delim(selected_file, header = FALSE, sep = "\t", skip = 64, fill = TRUE))
colnames(data) <- paste(data[1,])
data <- data[-c(1, 2), ]
columns_to_exclude <- c("time","date", "hhmmss", "averaging")
data <- data[, !colnames(data) %in% columns_to_exclude]
suppressWarnings(
  data[] <- lapply(data, as.numeric)
)
```


Main_graph
=======================================================================

Column {.sidebar}
-----------------------------------------------------------------------

```{r X_AXIS, message=FALSE}

selectInput('xcol1',
            HTML('<span style="font-size: 16px;"><b>X  Axis Variable</b></span>'),
            choices = names(data))

sliderInput('xmin', 'X Min Value', min = min(data[[1]]), max = max(data[[1]]), value = min(data[[1]]))
sliderInput('xmax', 'X Max Value', min = min(data[[1]]), max = max(data[[1]]), value = max(data[[1]]))


observeEvent(input$xcol1, {
  updateSliderInput(session, 'xmin', 'X Min Value',
                    min = min(data[[input$xcol1]]),
                    max = max(data[[input$xcol1]]),
                    value = min(data[[input$xcol1]]))

  updateSliderInput(session, 'xmax', 'X Max Value',
                    min = min(data[[input$xcol1]]),
                    max = max(data[[input$xcol1]]),
                    value = max(data[[input$xcol1]]))
})
```


```{r Y_AXIS, message=FALSE}
    
selectInput('ycol1', 
            HTML('<span style="font-size: 16px;"><b>Y  Axis Variable</b></span>'), 
            names(data),
            selected=names(data)[[4]])

sliderInput('ymin', 'Y Min Value', min = min(data[[3]]), max = max(data[[3]]), value = min(data[[3]]))
sliderInput('ymax', 'Y Max Value', min = min(data[[3]]), max = max(data[[3]]), value = max(data[[3]]))


observeEvent(input$ycol1, {
  updateSliderInput(session, 'ymin', 'Y Min Value',
                    min = min(data[[input$ycol1]]),
                    max = max(data[[input$ycol1]]),
                    value = min(data[[input$ycol1]]))

  updateSliderInput(session, 'ymax', 'Y Max Value',
                    min = min(data[[input$ycol1]]),
                    max = max(data[[input$ycol1]]),
                    value = max(data[[input$ycol1]]))
})
```

```{r UNITS_BUTTON, message=FALSE}
actionButton("open_website", "LI-6800 summary of symbols")

observeEvent(input$open_website, {
  browseURL("https://www.licor.com/env/support/LI-6800/topics/symbols.html")
})

HTML('<a href="mailto:loic.talide@slu.se" class="btn btn-primary">loic.talide@slu.se</a>')

```

Column
-----------------------------------------------------------------------

```{r GRAPH, message=FALSE, warning=FALSE}
selectedData1 <- reactive(
  data[, c(input$xcol1, input$ycol1)],
)

renderPlotly({
  par(mar = c(5.1, 4.1, 0, 1))
  p <- ggplot(selectedData1(), aes_string(x=input$xcol1, y=input$ycol1)) +
    geom_point(shape=20) +
    theme_bw() +
    ylim(input$ymin, input$ymax) +
    xlim(input$xmin, input$xmax)
  
  ggplotly(p)
       })
```


If you want to download only the data used to generate this graph, press on the "Download" button below.
```{r DOWNLOAD_DATA, message=FALSE}
 downloadHandler(
   filename = function() {
       filename <- input$file$name
       paste(input$xcol1, input$ycol1, ".csv", sep = "_")
   },
   content = function(file) {
     data <- selectedData1()
     write.csv(data, file, row.names = FALSE)
   }
 )

 uiOutput("downloadButton")
```


```{r EXTRACT_DATA, message=FALSE}
column_selector <- tagList(
  checkboxInput("select_all_columns", "Show all parameters in the options", FALSE),
  selectInput(
    inputId = "columns",
    label = NULL,
    choices = c("obs", "elapsed", "E", "A", "Ci", "gsw", "Fo", "Fm", "Fv/Fm", "Fs", "Fm'","ETR"), 
    selected = NULL,
    multiple = TRUE
  )
)

observeEvent(input$select_all_columns, {
  if (input$select_all_columns) {
    updateSelectInput(session, "columns", choices = colnames(data))
  } else {
    updateSelectInput(session, "columns", choices = c("obs", "elapsed", "E", "A", "Ci", "gsw", "Fo", "Fm", "Fv/Fm", "Fs", "Fm'","ETR"))
  }
})

output$exported_data <- downloadHandler(
  filename = function() {
    paste("exported_data_", file_date, ".csv", sep = "")
  },
  content = function(file) {
    selected_data <- data[, input$columns, drop = FALSE]
    write.csv(selected_data, file, row.names = FALSE, sep = ",")
  }
)

tabPanel("Export Data",
         column(6,
                h3("Export Data"),
                column_selector,
                downloadButton("exported_data", "Download")
         )
)
```


Fluorometer_data
=======================================================================

```{r FLUOFILES}
folder_path <- dirname(selected_file)
date_in_yyyymmdd <- format(as.Date(file_date), "%Y%m%d")
all_files <- list.files(folder_path)
xlsx_files <- all_files[str_detect(all_files, date_in_yyyymmdd) & str_detect(all_files, "\\.xlsx$")]

if (length(xlsx_files) == 0) {
  big_dataframe <- data.frame(SECS = numeric(), FLUOR = numeric(), FILE = character())
} else {
  timestamps <- data.frame(TIME = as.numeric(data$TIME))
  
  b5_values <- list()
  for (file in xlsx_files) {
    file_path <- file.path(folder_path, file)
    xls_data <- try(readxl::read_excel(file_path), silent = TRUE)
    if(inherits(xls_data, "try-error")) {
      next
    }
    b5_value <- as.numeric(xls_data[4, 2])
    b5_values[[file]] <- b5_value
  }
  
  b5_df <- data.frame(File = names(b5_values), B5_Value = unlist(b5_values))
  
  merge_with_precision <- function(df1, df2, by_column, precision = 5) {
    merged_df <- merge(df1, df2, by = NULL)  
    
    matched_rows <- abs(merged_df[[by_column[1]]] - merged_df[[by_column[2]]]) <= precision
    
    return(merged_df[matched_rows, ])
  }
  
  result <- merge_with_precision(b5_df, timestamps, by_column = c("B5_Value", "TIME"), precision = 5)
  
  interesting_files <- result$File
  
  
  big_dataframe <- data.frame(SECS = numeric(), FLUOR = numeric(), FILE = character())
  
  append_data <- function(file, folder_path, big_dataframe) {
    file_path <- file.path(folder_path, file)
    xls_data <- read_excel(file_path)
    
    xls_data$FILE <- file
    
    big_dataframe <<- rbind(big_dataframe, xls_data[, c("SECS", "FLUOR", "FILE")])
  }
  
  for (file in interesting_files) {
    append_data(file, folder_path, big_dataframe)
  }
}

ui <- fluidPage(
  titlePanel("Select Curves to Display"),
  sidebarLayout(
    sidebarPanel(
      checkboxGroupInput("file_choices", "Choose Files to Display:",
                         choices = unique(big_dataframe$FILE),
                         selected = unique(big_dataframe$FILE)),
      downloadButton("downloadData", "Download All Fluo Data")
    ),
    mainPanel(
      plotOutput("plot")
    )
  )
)

server <- function(input, output) {
  
  filtered_data <- reactive({
    big_dataframe %>%
      filter(FILE %in% input$file_choices)
  })
  
  output$plot <- renderPlot({
    ggplot(filtered_data(), aes(x = SECS, y = FLUOR, color = FILE)) +
      geom_line() +
      theme_bw() +
      labs(x = "SECS", y = "FLUOR")
  })
  output$downloadData <- downloadHandler(
    filename = function() {
      paste("big_dataframe_", Sys.Date(), ".csv", sep = "")
    },
    content = function(file) {
      write.csv(big_dataframe, file)
    })
}

shinyApp(ui = ui, server = server)

```











